@version: 3.38
options {
    keep-hostname(yes);
    use-dns(no);
};
source s_local { system(); internal(); };
destination d_tls {
    syslog("192.168.101.30"
        transport("tls")
        port(6514)
        tls(
            ca-dir("/etc/syslog-ng/certs")
            peer-verify(required-trusted)
        )
    );
};
log {
    source(s_local);
    destination(d_tls);
};
